project: migrate to AndroidX
ittianyu/BottomNavigationViewEx pull request #169
Opened 2019-06-05 13:20 UTC by tanliner

AndroidX

Signed-off-by: tanliner <lintan.spring@gmail.com>

2019-07-27 17:38 UTC, MZhuravsky commented
Need change the fields name to use reflection

2021-01-26 14:11 UTC, Activate256 requested changes
```

```

2021-01-26 14:14 UTC, Activate256 approved these changes

2021-04-17 22:44 UTC, Oscarwong79 commented
#169

2026-04-24 10:50 UTC, closed without merging